services:
 consul:
  image: hashicorp/consul:latest
  ports:
   - 8500:8500
  container_name: consul-container    

 product:
  build:
   context: .
   dockerfile: Microservice.ProductWebAPI/Dockerfile
  image: productapi
  ports:
   - 6001:8080 
  container_name: product-container 

 product2:
  build:
   context: .
   dockerfile: Microservice.ProductWebAPI/Dockerfile
  image: productapi
  ports:
   - 6002:8080 
  container_name: product-container2 

 basket:
  build:
   context: .
   dockerfile: Microservice.BasketWebAPI/Dockerfile
  image: basketapi
  ports:
   - 6010:8080
  container_name: basket-container

 auth:
  build:
   context: .
   dockerfile: Microservice.AuthWebAPI/Dockerfile
  image: authapi
  ports:
   - 9000:8080
  container_name: auth-container  

 ocelot:
  build:
   context: .
   dockerfile: Microservice.OcelotGateway/Dockerfile
  image: ocelotgateway
  ports:
   - 5001:8080
  container_name: ocelot-container